name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-11
      CXX: g++-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: |
        sudo apt-get update --quiet
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install cmake gcc-11 g++-11

    - name: Build project
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -- -j

    - name: Run tests
      run: |
        ctest --test-dir build/tests
