name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
      CC: gcc-11
      CXX: g++-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        sudo apt-get update --quiet
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get install cmake gcc-11 g++-11 libboost-dev
        pip install astropy
        python ./create_test_files.py

        curl -L https://github.com/xtensor-stack/xtl/archive/refs/tags/0.7.2.tar.gz | tar xz
        cmake -S xtl-0.7.2 -B xtl-0.7.2
        cmake --install xtl-0.7.2

        curl -L https://github.com/xtensor-stack/xtensor/archive/refs/tags/0.23.10.tar.gz | tar xz
        cmake -S xtensor-0.23.10 -B xtensor-0.23.10
        cmake --install xtensor-0.23.10

    - name: Build project
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build -- -j

    - name: Run tests
      run: |
        ./build/tests/tests --use-colour=yes
